In [ ]:
# tutorial on pyotorch from sentdex
# https://www.youtube.com/watch?v=BzcBsTou0C0

In [2]:
import numpy as np
import torch

In [3]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [5]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])
y

tensor([[0.7173, 0.1874, 0.1652, 0.3478, 0.3798],
        [0.6690, 0.9895, 0.2407, 0.6191, 0.3204]])

In [8]:
# reshape
y.view(1,10)

tensor([[0.7173, 0.1874, 0.1652, 0.3478, 0.3798, 0.6690, 0.9895, 0.2407, 0.6191,
         0.3204]])

In [9]:
y

tensor([[0.7173, 0.1874, 0.1652, 0.3478, 0.3798],
        [0.6690, 0.9895, 0.2407, 0.6191, 0.3204]])

In [10]:
y = y.view(1,10)
y

tensor([[0.7173, 0.1874, 0.1652, 0.3478, 0.3798, 0.6690, 0.9895, 0.2407, 0.6191,
         0.3204]])